# Step 1: Build stage
FROM node:14.16.0-alpine3.13 AS build-stage

WORKDIR /app
COPY package*.json ./

RUN npm install

COPY . .

ENV REAT_APP_API_URL=http://104.131.11.182:3001/api

RUN npm run build

# Step 2: Production stage
FROM nginx:1.12-alpine

# Copy all files from build-stage to be use din production
COPY  --from=build-stage /app/build /usr/share/nginx/html

# Expose default port for web traffic
EXPOSE 80

ENTRYPOINT [ "nginx", "-g", "daemon off;" ]